# -*- coding: utf-8 -*-
"""w7-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b4emkV1jVpv01wqzm2A9_mVMxXcs08rv
"""

!pip install pyDatalog

from pyDatalog import pyDatalog

pyDatalog.create_terms('big,small,brown,black,gray,dark,X,Y')
+big('bear')
+big('elephant')
+small('cat')
+brown('bear')
+black('cat')
+gray('elephant')

dark(X)<=black(X)
dark(X)<=brown(X)

(dark(Y) & big(Y))